# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose

services:
  server:
    build:
      context: .
      target: development
    # Load environment variables from .env.docker file
    env_file:
      - .env.docker
    command: node --experimental-transform-types --watch apps/api/src/index.ts
    ports:
      - 3000:3000
      - 9229:9229 # For debugging purpose
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    secrets:
      - db-password
      - jwt-secret
      - redis-password
    volumes:
      - ./apps/api/src:/usr/src/app/apps/api/src
      - ./packages:/usr/src/app/packages
  worker:
    build:
      context: .
      target: development
    env_file:
      - .env.docker
    command: node --watch --experimental-transform-types apps/worker/src/index.ts
    secrets:
      - db-password
      - jwt-secret
      - redis-password
    volumes:
      - ./apps/worker/src:/usr/src/app/apps/worker/src
      - ./packages:/usr/src/app/packages
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: unless-stopped
  db:
    image: postgres:16
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    # Load environment variables from .env.docker file
    env_file:
      - .env.docker
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7-alpine
    restart: always
    secrets:
      - redis-password
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: sh -c "redis-server --requirepass $$(cat /run/secrets/redis-password)"
    healthcheck:
      test:
        [
          "CMD",
          "sh",
          "-c",
          "redis-cli -a $$(cat /run/secrets/redis-password) ping",
        ]
      interval: 5s
      timeout: 3s
      retries: 5
volumes:
  db-data:
  redis-data:
secrets:
  db-password:
    file: secrets/db_password.txt
  jwt-secret:
    file: secrets/jwt_secret.txt
  redis-password:
    file: secrets/redis_password.txt
